export const CHARACTER_BASE_SPEED = 0.25;
export const CHARACTER_HEADING_LOOKAHEAD = 0.1;
export const CHARACTER_BASE_ANIMATION_SPEED = 0.5;
export const CHARACTER_MIN_SPEED = 0.5;
export const CHARACTER_MAX_SPEED = 2;
