import type { PlacedTile } from "../types";

interface RoadLayout {
  id: string;
  name: string;
  tiles: readonly PlacedTile[];
}

export const ROAD_LAYOUTS: readonly RoadLayout[] = [
  {
    id: "pentagon-loop",
    name: "五角形環道",
    tiles: [
      { q: 2, r: -4, tileId: "path-corner-sharp", rotation: 2 },
      { q: 2, r: -3, tileId: "path-corner", rotation: 5 },
      { q: 3, r: -3, tileId: "path-corner", rotation: 2 },
      { q: 3, r: -2, tileId: "path-corner", rotation: 5 },
      { q: 4, r: -2, tileId: "path-corner", rotation: 2 },
      { q: 4, r: -1, tileId: "path-corner", rotation: 1 },
      { q: 3, r: 0, tileId: "path-corner", rotation: 4 },
      { q: 3, r: 1, tileId: "path-corner", rotation: 1 },
      { q: 2, r: 2, tileId: "path-straight", rotation: 1 },
      { q: 1, r: 3, tileId: "path-corner", rotation: 0 },
      { q: 0, r: 3, tileId: "path-straight", rotation: 0 },
      { q: -1, r: 3, tileId: "path-straight", rotation: 0 },
      { q: -2, r: 3, tileId: "path-straight", rotation: 0 },
      { q: -3, r: 3, tileId: "path-straight", rotation: 0 },
      { q: -4, r: 3, tileId: "path-corner", rotation: 5 },
      { q: -4, r: 2, tileId: "path-corner", rotation: 4 },
      { q: -3, r: 1, tileId: "path-corner", rotation: 1 },
      { q: -3, r: 0, tileId: "path-straight", rotation: 2 },
      { q: -3, r: -1, tileId: "path-corner", rotation: 4 },
      { q: -2, r: -2, tileId: "path-corner", rotation: 3 },
      { q: -1, r: -2, tileId: "path-corner", rotation: 0 },
      { q: 0, r: -3, tileId: "path-corner", rotation: 3 },
      { q: 1, r: -3, tileId: "path-corner", rotation: 0 },
    ],
  },
  {
    id: "winding-line",
    name: "蜿蜒直線",
    tiles: [
      { q: -4, r: 1, tileId: "path-start", rotation: 4 },
      { q: -3, r: 0, tileId: "path-straight", rotation: 1 },
      { q: -2, r: -1, tileId: "path-corner", rotation: 3 },
      { q: -1, r: -1, tileId: "path-straight", rotation: 0 },
      { q: 0, r: -1, tileId: "path-corner", rotation: 2 },
      { q: 0, r: 0, tileId: "path-straight", rotation: 2 },
      { q: 0, r: 1, tileId: "path-corner", rotation: 5 },
      { q: 1, r: 1, tileId: "path-straight", rotation: 0 },
      { q: 2, r: 1, tileId: "path-corner", rotation: 0 },
      { q: 3, r: 0, tileId: "path-straight", rotation: 1 },
      { q: 4, r: -1, tileId: "path-corner", rotation: 1 },
      { q: 4, r: -2, tileId: "path-straight", rotation: 2 },
      { q: 4, r: -3, tileId: "path-corner", rotation: 2 },
      { q: 3, r: -3, tileId: "path-straight", rotation: 0 },
      { q: 2, r: -3, tileId: "path-straight", rotation: 0 },
      { q: 1, r: -3, tileId: "path-straight", rotation: 0 },
      { q: 0, r: -3, tileId: "path-start", rotation: 3 },
    ],
  },
  {
    id: "cross-junction",
    name: "十字岔路",
    tiles: [
      { q: -4, r: 0, tileId: "path-start", rotation: 3 },
      { q: -3, r: 0, tileId: "path-straight", rotation: 0 },
      { q: -2, r: 0, tileId: "path-straight", rotation: 0 },
      { q: -1, r: 0, tileId: "path-straight", rotation: 0 },
      { q: 0, r: 0, tileId: "path-intersectionE", rotation: 0 },
      { q: 1, r: 0, tileId: "path-straight", rotation: 0 },
      { q: 2, r: 0, tileId: "path-straight", rotation: 0 },
      { q: 3, r: 0, tileId: "path-straight", rotation: 0 },
      { q: 4, r: 0, tileId: "path-start", rotation: 0 },
      { q: 0, r: -4, tileId: "path-start", rotation: 2 },
      { q: 0, r: -3, tileId: "path-straight", rotation: 2 },
      { q: 0, r: -2, tileId: "path-straight", rotation: 2 },
      { q: 0, r: -1, tileId: "path-straight", rotation: 2 },
      { q: 0, r: 1, tileId: "path-straight", rotation: 2 },
      { q: 0, r: 2, tileId: "path-straight", rotation: 2 },
      { q: 0, r: 3, tileId: "path-straight", rotation: 2 },
      { q: 0, r: 4, tileId: "path-start", rotation: 5 },
    ],
  },
  {
    id: "irregular-loop",
    name: "不規則圓形環道",
    tiles: [
      { q: 4, r: 0, tileId: "path-straight", rotation: 2 },
      { q: 4, r: -1, tileId: "path-straight", rotation: 2 },
      { q: 4, r: -2, tileId: "path-corner", rotation: 2 },
      { q: 3, r: -2, tileId: "path-corner", rotation: 5 },
      { q: 3, r: -3, tileId: "path-corner", rotation: 2 },
      { q: 2, r: -3, tileId: "path-corner", rotation: 5 },
      { q: 2, r: -4, tileId: "path-corner", rotation: 2 },
      { q: 1, r: -4, tileId: "path-corner", rotation: 3 },
      { q: 0, r: -3, tileId: "path-corner", rotation: 0 },
      { q: -1, r: -3, tileId: "path-corner", rotation: 3 },
      { q: -2, r: -2, tileId: "path-corner", rotation: 0 },
      { q: -3, r: -2, tileId: "path-corner-sharp", rotation: 3 },
      { q: -3, r: -1, tileId: "path-corner", rotation: 1 },
      { q: -4, r: 0, tileId: "path-corner", rotation: 4 },
      { q: -4, r: 1, tileId: "path-straight", rotation: 2 },
      { q: -4, r: 2, tileId: "path-corner", rotation: 5 },
      { q: -3, r: 2, tileId: "path-corner", rotation: 2 },
      { q: -3, r: 3, tileId: "path-corner", rotation: 5 },
      { q: -2, r: 3, tileId: "path-corner", rotation: 2 },
      { q: -2, r: 4, tileId: "path-corner", rotation: 5 },
      { q: -1, r: 4, tileId: "path-corner", rotation: 0 },
      { q: 0, r: 3, tileId: "path-corner", rotation: 3 },
      { q: 1, r: 3, tileId: "path-corner", rotation: 0 },
      { q: 2, r: 2, tileId: "path-corner", rotation: 3 },
      { q: 3, r: 2, tileId: "path-corner", rotation: 0 },
      { q: 4, r: 1, tileId: "path-corner", rotation: 1 },
    ],
  },
  {
    id: "four-grid",
    name: "四方格",
    tiles: [
      { q: -2, r: -2, tileId: "path-corner-sharp", rotation: 3 },
      { q: -1, r: -2, tileId: "path-straight", rotation: 0 },
      { q: 0, r: -2, tileId: "path-intersectionC", rotation: 0 },
      { q: 1, r: -2, tileId: "path-straight", rotation: 0 },
      { q: 2, r: -2, tileId: "path-corner", rotation: 2 },
      { q: -2, r: 0, tileId: "path-intersectionB", rotation: 5 },
      { q: -1, r: 0, tileId: "path-straight", rotation: 0 },
      { q: 0, r: 0, tileId: "path-intersectionE", rotation: 0 },
      { q: 1, r: 0, tileId: "path-straight", rotation: 0 },
      { q: 2, r: 0, tileId: "path-intersectionB", rotation: 2 },
      { q: -2, r: 2, tileId: "path-corner", rotation: 5 },
      { q: -1, r: 2, tileId: "path-straight", rotation: 0 },
      { q: 0, r: 2, tileId: "path-intersectionC", rotation: 3 },
      { q: 1, r: 2, tileId: "path-straight", rotation: 0 },
      { q: 2, r: 2, tileId: "path-corner-sharp", rotation: 0 },
      { q: -2, r: -1, tileId: "path-straight", rotation: 2 },
      { q: -2, r: 1, tileId: "path-straight", rotation: 2 },
      { q: 0, r: -1, tileId: "path-straight", rotation: 2 },
      { q: 0, r: 1, tileId: "path-straight", rotation: 2 },
      { q: 2, r: -1, tileId: "path-straight", rotation: 2 },
      { q: 2, r: 1, tileId: "path-straight", rotation: 2 },
    ],
  },
];
